### ISSUE TITLE
[FE] Add Switch story

### ISSUE THREAD

**Issue by cungminh2710** [cungminh2710/coderum.dev#53]
[Storybook](https://storybook.js.org/) is a front-end workshop for building UI components and pages in isolation. It allows a quick preview of the UI components and functions as a UI documentation playground.

Currently, our UI design system has components in `packages/ui` which is based on [shadcn/ui](https://ui.shadcn.com/docs/components/accordion)

We should add a storybook for the Switch component to `packages/ui/src/stories` ([example](https://github.com/cungminh2710/coderum.dev/tree/main/packages/ui/src/stories))

**Comment by HoangVNH** [comment]
Hi @cungminh2710, I can't assign this issue to myself, can you help me close this issue?
